- name: Allow OpenSSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow Postgres
  community.general.ufw:
    rule: allow
    port: '5432'
    proto: tcp

- name: Allow Zookeeper
  community.general.ufw:
    rule: allow
    port: '2181'
    proto: tcp

- name: Allow Solr
  community.general.ufw:
    rule: allow
    port: '8983'
    proto: tcp

- name: Allow ActiveMQ
  community.general.ufw:
    rule: allow
    port: '61616'
    proto: tcp

- name: Allow Samba
  community.general.ufw:
    rule: allow
    name: samba

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: allow